// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucsxwhnscgbcshaghyrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjc3h3aG5zY2diY3NoYWdoeXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODk2NTQsImV4cCI6MjA2ODI2NTY1NH0.kaxOo5GxtF-ONAP33wEl3RFTZEtoqk41ZOd8uczsUGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});